#!/bin/bash

function assert_git_is_clean() {
    status=$(git status --porcelain)

    if [ -n "${status}" ]; then
	echo "Working directory is not clean. Aborting..."
	exit 1
    fi
}

assert_git_is_clean

lein do clean, uberimage || exit 1

IMAGE_NAME=mastodonc/kixi.hecuba
TAG=git-$(git rev-parse --short=12 HEAD)

# FIXME: the tagging is a little suspect here, 'cos we
#        don't depend on a fixed version of the parent
#        docker repos. ie. changes to the parent repo 
#        will still have the same git sha here. 
docker tag -f "${IMAGE_NAME}" "${IMAGE_NAME}:latest" && \
docker tag -f "${IMAGE_NAME}" "${IMAGE_NAME}:${TAG}" && \
docker push "${IMAGE_NAME}"
